///////////////////////////////////////////////////////////
//
//  VFileNotFoundException.h
//  Implementation of the Class VFileNotFoundException
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2003 01:09:21
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


#if !defined(VFileNotFoundException_10E8ED00_721A_4b0d_A6D5_6090CBE13488__INCLUDED_)
#define VFileNotFoundException_10E8ED00_721A_4b0d_A6D5_6090CBE13488__INCLUDED_

#include "VIOException.h"

class VFileNotFoundException : public VIOException
{
private:

public:
	VFileNotFoundException(std::string in_strReason, std::string in_strFileName, vuint in_nLineNumber);

	virtual ~VFileNotFoundException();
};

#endif // !defined(VFileNotFoundException_10E8ED00_721A_4b0d_A6D5_6090CBE13488__INCLUDED_)
