///////////////////////////////////////////////////////////
//
//  VFileNotFoundException.cpp
//  Implementation of the Class VFileNotFoundException
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2003 01:09:21
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////

#include "VFileNotFoundException.h"

using std::string;


VFileNotFoundException::~VFileNotFoundException(){

}


VFileNotFoundException::VFileNotFoundException(string in_strReason, string in_strFileName, vuint in_nLineNumber)
	: VIOException(in_strReason, in_strFileName, in_nLineNumber)
{

}
