///////////////////////////////////////////////////////////
//
//  VIOException.h
//  Implementation of the Class VIOException
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2003 00:18:10
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


#if !defined(VIOException_6B7D27C8_F8C3_4242_8535_5091BB0B25F8__INCLUDED_)
#define VIOException_6B7D27C8_F8C3_4242_8535_5091BB0B25F8__INCLUDED_

#include <Error/VException.h>

#include <string>

class VIOException : public VException
{
private:
	VIOException();

public:
	virtual ~VIOException();
	VIOException(std::string in_strReason, std::string in_strFileName, vuint in_nLineNumber);
};

#endif // !defined(VIOException_6B7D27C8_F8C3_4242_8535_5091BB0B25F8__INCLUDED_)
