///////////////////////////////////////////////////////////
//
//  VIOException.cpp
//  Implementation of the Class VIOException
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2003 00:18:10
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////

#include "VIOException.h"

using std::string;

VIOException::~VIOException(){

}


VIOException::VIOException(){

}


VIOException::VIOException(string in_strReason,string in_strFileName,vuint in_nLineNumber)
	: VException(in_strReason, in_strFileName, in_nLineNumber)
{

}


