/******************************************************************************
 * The following code was generated by the mental mill(tm)                    *
 *                                                                            *
 * Copyright 1986-2007 by mental images GmbH, Fasanenstr. 81, D-10623         *
 * Berlin, Germany. All rights reserved.                                      *
/*****************************************************************************/

uniform float flip_normal;

varying vec3 position;
varying vec3 normal;
varying vec4 tex_coord0;
varying vec4 tex_coord1;
varying vec4 tex_coord2;
varying vec4 tex_coord3;

void main()
{
	gl_Position = ftransform();
	position = (gl_ModelViewMatrix * gl_Vertex).xyz;
	normal = gl_NormalMatrix * gl_Normal;
	tex_coord0 = gl_MultiTexCoord0;
	tex_coord1 = gl_MultiTexCoord1;
	tex_coord2 = gl_MultiTexCoord2;
	tex_coord3 = gl_MultiTexCoord3;

	if( flip_normal > 0.0 ) {
		gl_FrontColor = vec4(1.0);
		gl_BackColor  = vec4(0.0);
	} else {
		gl_FrontColor = vec4(0.0);
		gl_BackColor  = vec4(1.0);
	}
}
