///////////////////////////////////////////////////////////
//
//  VNullCheckPol.h
//  Implementation of the Class VNullCheckPol
//  Generated by Enterprise Architect
//  Created on:      16-Feb-2003 14:05:52
//  Original author: sheijk
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////

// Warnung fuer gekappte Template Methoden Namen ausschalten
#pragma warning( disable : 4786)

#if !defined(VNullCheckPol_2D1E555E_9F72_45d4_B7F5_777D635403AD__INCLUDED_)
#define VNullCheckPol_2D1E555E_9F72_45d4_B7F5_777D635403AD__INCLUDED_

#include <Error/VException.h>

template<typename T>
class VNullCheckPol
{

public:
	VNullCheckPol() {}
	~VNullCheckPol() {}

public:
	static inline vbool IsValid(T in_Val)
	{
		return 0 != in_Val;
	}

	static inline void Check(T in_Val)
	{
		if( ! IsValid(in_Val) )
		{
			V3D_THROW(VException, "NullPointer Access");
		}
	}
};

#endif // !defined(VNullCheckPol_2D1E555E_9F72_45d4_B7F5_777D635403AD__INCLUDED_)
