///////////////////////////////////////////////////////////
//
//  IVXMLWriter.h
//  Implementation of the Interface IVXMLWriter
//  Generated by Enterprise Architect
//  Created on:      29-May-2003 00:25:24
//  Original author: sheijk
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


#ifndef IVXMLWRITER_H
#define IVXMLWRITER_H

#include <V3d/Core/VTypes.h>

namespace v3d{
namespace xml{


class IVXMLWriter
{

public:
	virtual void WriteDeclaration(VStringParam FileName) =0;
	/*
	* Creates a new xml element (<Name)
	*/
	virtual void OpenElement(VStringParam name) =0;
	/*
	* Closes the last opened element. (/> oder </Name>)
	*/
	virtual void CloseElement(VStringParam name) =0;
	/*
	* Adds an attribute to the current element. May only be called directly after
	* OpenElement
	*/
	virtual void AddAttribute(VStringParam name, VStringParam value,...) =0;
	/*
	* Adds a comment
	*/
	virtual void AddComment(VStringParam text) =0;
	/*
	* Adds a text
	*/
	//virtual void AddText(char* text) =0;
	/*
	* Finishes writing. Cache will be written to disk.
	*/
	virtual void Close() =0;

};

}
}

#endif
